### ISSUE TITLE
-v /sys/fs/cgroup:/sys/fs/cgroup:ro

### ISSUE THREAD

**Issue by spurin** [AkihiroSuda/containerized-systemd#10]
Hi @AkihiroSuda 

Appreciate your efforts on this, the project is great and am finding it useful for a use-case I have.

Running systemd in Docker typically involves the use of '-v /sys/fs/cgroup:/sys/fs/cgroup:ro' volume pass thru from the parent.

Are you able to advise on why this is not needed here?

Thanks

**Comment by AkihiroSuda** [comment]
- /sys/fs/cgroup is mounted by default with recent version of Docker, so `-v /sys/fs/cgroup` is not needed
- systemd requires rw access for `/sys/fs/cgroup`, so `:ro` should be not be used

**Comment by spurin** [comment]
Thanks @AkihiroSuda 

Grateful for your feedback on this.
